import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const darkerGrostesque = localFont({
  src: './fonts/DarkerGrotesque.ttf',
  variable: '--font-darker-grotesque',
  weight: '300 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${darkerGrostesque.variable} antialiased`}>{children}</body>
    </html>
  );
}
