import type { Metadata } from 'next';
import { Darker_Grotesque } from 'next/font/google';
import './globals.css';

const darkerGrostesque = Darker_Grotesque({
  subsets: ['latin'],
  variable: '--font-darker-grotesque',
  weight: ['300', '500', '600', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${darkerGrostesque.variable} antialiased`}>{children}</body>
    </html>
  );
}
